### ISSUE TITLE
TextureName is broken

### ISSUE THREAD

**Issue by Kippykip** [markcwm/openb3d.mod#10]
TextureName returns a bunch of weird characters, but not the file path of the loaded texture like it should.
Returns "��"
when it should return something like
"wcrate.jpg"

**Comment by markcwm** [comment]
Yes it was, thanks. It should be fixed now in the latest 172dc1bce589f07b02e20f82d66012fb7db8d172. I never noticed, it was "return tex->TextureName().c_str()" I think this was a temp string and went out of scope.

**Comment by Kippykip** [comment]
Confirmed to be fixed now, cheers!
