### ISSUE TITLE
Wrong links in the BlitzMax help files

### ISSUE THREAD

**Issue by MidimasterSoft** [markcwm/openb3d.mod#24]
The OpenB3D commands are highlighted and I get into the BlitzMax-HELP with F1.

If I open the help for command **Graphics3D** I see the behind the keyword "Description" a link to "Online doc". This link goes to...

http://www.blitzbasic.com/b3ddocs/command.php?name=Graphics3D

....but this is of course not online anymore.

**Comment by markcwm** [comment]
Hi Midimaster,

thanks, I recently updated these in the core but forgot about B3dglgraphics. This has been added to the latest commit 9de8b2046c439d07aed21e425c48f95fa9281199

**Comment by MidimasterSoft** [comment]
thanks, works now
