### ISSUE TITLE
FreeEntity crashes with models that contain bones

### ISSUE THREAD

**Issue by Kippykip** [markcwm/openb3d.mod#4]
Doesn't matter whether you load with LoadMesh and LoadAnimMesh.
If the model file loaded contains bones and you use FreeEntity, it will crash BlitzMax.
Thread with more detail here:
http://www.syntaxbomb.com/index.php/topic,3663.0.html

Example here:
[crashexample2.zip](https://github.com/markcwm/openb3d.mod/files/1480379/crashexample2.zip)

Good luck! :)

**Comment by markcwm** [comment]
Thanks Kip, the latest commit ff8f805cc324925cf80fe370c0a97a646be4b41c should fix this now. Also fixed is the MD2 crashing on exit issue.
