### ISSUE TITLE
Size_t overload warning

### ISSUE THREAD

**Issue by HenriVi** [markcwm/openb3d.mod#7]
Hi Mark,

compiling your mod for bmx-ng gives a warning in the title. As this might create some wondering for a new user.

You could edit the file stbimageloader.mod\stbimageloader.bmx , line 44 and change:

```BlitzMax
Local bufLen:Int = StreamSize(stream) 
```
to:

```BlitzMax
?bmxng
     Local bufLen:Size_T = StreamSize(stream)
?Not bmxng
     Local bufLen:Int = StreamSize(stream)
? 
```

-Henri

**Comment by markcwm** [comment]
Thanks Henri! Fix was added to the latest commit 434403d47aee3f52afa69c558424d14291bf7d67.
